### ISSUE TITLE
Value in model object doesn't changed

### ISSUE THREAD

**Issue by vashchenkov** [adopted-ember-addons/ember-pikaday#132]
I try to use pickaday-input over the model object but it doesn't change property of model object. I can change the value only by using action. 
`{{pikaday-input value=model.startDate format='DD.MM.YYYY' useUTC=true onSelection=(action 'updateStartDate')}}`

Update another property of the model working fine
`{{input type="checkbox" name="published" checked=model.published}}`

May be I do something wrong?

**Comment by duizendnegen** [comment]
Hm, surprising, to be honest. I've had some issues with `useUTC` before, can you verify that the same behavior is happening without?

If it does, could you replicate it in a small demo application? I looked through my applications and everywhere use `value=checkin`,  not a deeper reference, having aliases these elements.

**Comment by vashchenkov** [comment]
Thanks for quick answer.
No it doesn't work. Even I if remove useUTC=true.
I try to do small application with mirage tommorow

**Comment by vashchenkov** [comment]
Here is my repo with simple app
https://github.com/vashchenkov/ember-test-app
To check what is happens open th e url http://localhost:4200/news/50 or http://localhost:4200/news/200
There are data for this news. With ember chrome extention You can see then neither startDate and finishDate doesn't change.

**Comment by falkon** [comment]
I, too, does not change property of model object.

**Comment by vashchenkov** [comment]
I found somthing strange. I try to create component for interval date filter
interval-filter.hbs:

    {{pikaday-input value=startDate format='DD.MM.YYYY' onSelection=(action 'updateStartDate')}} - {{pikaday-input value=finishDate format='DD.MM.YYYY'}}

interval-filter.js

    import Ember from "ember";

    export default Ember.Component.extend({
	didReceiveAttrs() {
		this._super(...arguments);
		this.set('errors', []);

		console.log(this.get('startDate'));
	},
	didRender() {
		this._super(...arguments);
		console.log("rendered");
	},
	actions: {
		updateStartDate(value) {
			console.log(this.get('startDate'));
		}
	}

    });


When component is inited I show in console:
    
     interval-filter.js:7 Sat Feb 25 2017 00:00:00 GMT+0300 (RTZ 2 (зима))

And when I changed the date in component nothing changed:

    interval-filter.js:15 Sat Feb 25 2017 00:00:00 GMT+0300 (RTZ 2 (зима))

**Comment by Aaronfischer** [comment]
I'm having the same issue with 2.2.1 and 2.2.0, `{{pikaday-input value=model.publishedAt format="MM-DD-YYYY"}}` does not update the model property...

**Comment by FenzaFenz** [comment]
Same issue, 
Ember      : 2.10.2
Ember Data : 2.11.0

**Comment by duizendnegen** [comment]
As I have no active projects with this dependency anymore, I probably won't be getting to it anytime soon. Welcoming a PR which fixes this.

**Comment by HuggableSquare** [comment]
From what I can tell, this functionality was changed in 2.x, here's the commit where it happened: https://github.com/edgycircle/ember-pikaday/commit/2d8cf80239488b92de58adf9a7b436b621f5391b.

I guess in 2.x we're supposed to use the `onSelection` action instead of binding. 🙁

**Comment by milestinsley** [comment]
The `ember-pikaday` component has moved to a "data down, actions up" approach, consistent with the general direction in which Ember components are going.

Therefore, after upgrading to 2.x, you need to set both the `value` argument and pass in some kind of action. So, now, `value` sets the date shown in the component ("data down") and the `onSelection` action fires when a date is selected ("actions up"). Therefore you can use the `mut` helper to change your property on your model. For example:

```
{{pikaday-input value=model.someDateProp onSelection=(action (mut model.someDateProp))}}
```

**Comment by ddengler** [comment]
i guess this can be closed? setting with onSelection works as expected

**Comment by alexlafroscia** [comment]
> i guess this can be closed? setting with onSelection works as expected

I think that's the right approach for this issue -- `onSelection` is the way to go, and the example that @milestinsley shows above is exactly what people should do.
