### ISSUE TITLE
minDate and maxDate couldn't be nullable

### ISSUE THREAD

**Issue by remithomas** [adopted-ember-addons/ember-pikaday#154]
`minDate` and `maxDate` couldn't be nullable, this introduces a wrong use. You couldn't change the value of your `minDate` from value to null. It will keep your previous date.

Here is the problem: 
https://github.com/edgycircle/ember-pikaday/blob/075e023e2f3c5cfb554cb6c508dfba196067a66c/addon/mixins/pikaday.js#L125

**Comment by duizendnegen** [comment]
Welcoming a PR
