### ISSUE TITLE
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format

### ISSUE THREAD

**Issue by tsteuwer** [adopted-ember-addons/ember-pikaday#156]
```
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 06/30/2017, _f: undefined, _strict: undefined, _locale: [object Object]
```

This issue happens due to: https://github.com/edgycircle/ember-pikaday/blob/master/addon/mixins/pikaday.js#L121

We should use the `format` value that's passed in as a value *if* set. Or, we should start requiring people specify a format since this functionality will eventually be removed if not in RFC2822 or ISO date format.

**Comment by krishanjangir** [comment]
Below works for me to remove RFC2822 warnings

Use moment(String, FormatString) to convert string to date.

 var newDt = Moment(this.state.dob,"MM/DD/YY")
And below code from date to String

var dt = Moment(newDt).format("YYYY-MM-DD") 
By this way it will not show warning messages.

**Comment by talha08** [comment]
use like this
` Moment(new Date(date)).format('MM/DD/YYYY')`

**Comment by Yangxiucheng1002** [comment]
But after I set it up, I still report an error.
![image](https://user-images.githubusercontent.com/29248652/51815143-073b3580-22fa-11e9-8827-3af0e3932f0e.png)

**Comment by cah-danmonroe** [comment]
you need to put the format in the moment constructor...  `moment(new Date, "YYYY-MM-DD")`

see [https://momentjs.com/docs/#/parsing/string-format/](https://momentjs.com/docs/#/parsing/string-format/)

**Comment by budostylz** [comment]
You going to have to instantiate a date and pass it to the moment constructor to prevent the warning.
moment( new Date ).format('MM/DD/YYYY')  --> 5/19/2020. If you need a custom date, you will have to create a date object from that and pass to moment constructor.

**Comment by YogeshSonar** [comment]
Hi,

_If you want to remove the below warning:
Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged and will be removed in an upcoming major release. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 06/30/2017, _f: undefined, _strict: undefined, _locale: [object Object]_

then use below line of code, it works for me, also you can use in node.js model.js file.

`moment(new Date()).utc().format("YYYY-MM-DD HH:mm:ss")`

Thanks

**Comment by BonBonSlick** [comment]
```
   val = moment().utc().isSameOrBefore(moment('2020-10-10 10:10:10', 'YYYY-DD-MM hh:mm:ss')); // false
            val = moment().isSameOrBefore(moment('2020-10-10 10:10:10')); // true but with warning 
```
something wrong here, formatting breaks isSameOrBefore / isSameOrAfter features
```

moment.js?c1df:283 Deprecation warning: value provided is not in a recognized RFC2822 or ISO format. moment construction falls back to js Date(), which is not reliable across all browsers and versions. Non RFC2822/ISO date formats are discouraged. Please refer to http://momentjs.com/guides/#/warnings/js-date/ for more info.
Arguments: 
[0] _isAMomentObject: true, _isUTC: false, _useUTC: false, _l: undefined, _i: 2021-06-30 13:45:11 , _f: undefined, _strict: undefined, _locale: [object Object]
```

**Comment by pradeeprelwani21** [comment]
> new Date

thank you, it works.

**Comment by cuibap1907** [comment]
I have the same problem, I tried to convert the date to UTC string by using toUTCString().
date.toUTCString()
Then you can get date with your custom format.
Here is an example:
getFormatDate(date.toUTCString(), "DD/MM/YYYY")
Hope it help.
