### ISSUE TITLE
_moment2.default.utc is not a function

### ISSUE THREAD

**Issue by rizkysyazuli** [adopted-ember-addons/ember-pikaday#161]
I got this error when setting `useUTC=true`. might be related, in the component where i use ember-pikaday, i've also have [ember-moment](https://github.com/stefanpenner/ember-moment).

**Comment by duizendnegen** [comment]
Could you replicate this in https://ember-twiddle.com/?

**Comment by alexlafroscia** [comment]
Going to close this until @rizkysyazuli responds with a reproduction
