### ISSUE TITLE
Keyboard Input triggers `onSelection` action

### ISSUE THREAD

**Issue by rsoo** [adopted-ember-addons/ember-pikaday#166]
When pikaday input is open and a user uses a keyboard input (`up`, `down`, `left`, `right` arrow), it triggers the onSelection action even if no date has been selected via `enter`

**Comment by jakenewby** [comment]
confirmed.. happening to me as well

**Comment by IAmJulianAcosta** [comment]
You just need to update to `2.2.4` and pass that parameter:

```
    {{pikaday-inputless
      options=(hash keyboardInput=false)
    }}
```

**Comment by alexlafroscia** [comment]
Seeing as there's a solution documented above, I'm going to close this.

Thanks for the fix, @IAmJulianAcosta !
