### ISSUE TITLE
Selecting days 1-11 of the month changes the format in the display field from DD/MM/YYYY to MM/DD/YYYY

### ISSUE THREAD

**Issue by abueloshika** [adopted-ember-addons/ember-pikaday#168]
`<div class="col-sm-3"><label>Date From:</label>{{pikaday-input locale=en value=dateFrom  format='DD/MM/YYYY' class="form-control" name="dateFrom" onSelection=(action 'onChangeDateFrom') }}</div>
`
In the date field using the above code, if a user selects a date between the 1st and 11th of the month the format of the date in the displpay field reverts from DD/MM/YYYY to MM/DD/YYYY. The date picker then behaves as if this is the selected date (ie if the user clicks back into the field, it will display the month from the MM/DD/YYYY format.)

I have these values being placed as query parameters in the URL string and they are inserted there correctly in a DD-MM-YYYY format, but even if the param is correct the field still displays the MM/DD/YYYY format.

**Comment by thiberaw** [comment]
check my comment in https://github.com/edgycircle/ember-pikaday/issues/162

**Comment by abueloshika** [comment]
Thank you for your response but I'm not quite sure how I can implement your recommendation in the above. I don;t have a fixed value I can pass in the moment(value) section because this is happening immediately when a user clicks into the date field.

Are you able to provide any advice on implementing your solution to the helper code in the OP?

**Comment by afriqs** [comment]
Hi,
Same issue here but we found that `ember-pikaday` works well with `DD-MM-YYYY` and `DD*MM*YYYY` format but not with `DD/MM/YYYY` (it reverses to `MM/DD/YYYY`): perhaps an *interpretation* issue with `/` :thinking:
