### ISSUE TITLE
Up for adoption?

### ISSUE THREAD

**Issue by cah-danmonroe** [adopted-ember-addons/ember-pikaday#195]
When an original owner no longer has time to maintain the addon, there is a place where the addon can be "put up for adoption."  Melanie Sumner has created [adopted-ember-addons](https://github.com/adopted-ember-addons).  

Would you consider allowing us to adopt ember-pikaday so that the addon may continue to provide useful service to the community?

**Comment by jrjohnson** [comment]
If you're in a place to take up maintenance for this package take a look at https://www.npmjs.com/policies/disputes 
NPM has a clear process for adopting an abandoned package.

**Comment by scottkidder** [comment]
Hi @stravid would you be willing to let us adopt this addon? It's a great addon and I think we have more than enough interest that we will have no trouble maintaining this as a community effort.

**Comment by jonnii** [comment]
I think adding a few contributors to the project and giving them the ability to publish to NPM would be fine in this case, there's no reason to transfer ownership of the repo in my opinion. This is your project so you maybe have a feel for who would be a good steward for the project going forward, if not I'm happy to volunteer to help coordinate.

**Comment by alexlafroscia** [comment]
My proposal for the add-on's maintenance: 

- Transfer over to the [Adopted Addons](https://github.com/adopted-ember-addons) organization, so that no individual or company is specifically responsible going forward (I have the permissions required to fork from here into that org)
- Transfer the NPM ownership to the `adopted-ember-addons` organization and manage read/write access from there

If people are interested in taking an active role in managing the publishing of the addon to NPM, we can add them to the organization on NPM and manage the permissions from there, or just set up auto-deploy-on-merge and forget about doing it manually

**Comment by jonnii** [comment]
@alexlafroscia I think that's the best solution.

**Comment by stravid** [comment]
@alexlafroscia thank you for the detailed proposal. We discussed this internally and got the green light to push this forward as you outlined.

I just invited you as an admin so you can transfer the repository.

Regarding npm I'm not sure how to do that. Do I add you as a maintainer? (If yes, what is your username?)

**Comment by alexlafroscia** [comment]
Awesome, I'll get started on that!

On the NPM front, this is my first time trying to transfer a package to an organization, so I'm not 100% sure. I _think_ this might do the trick:

```bash
npm owner add adopted-ember-addons ember-pikaday
```

Instead of manually managing maintainers, the plan is to manage read/write access through the organization.

**Comment by alexlafroscia** [comment]
Transfer complete!

**Comment by stravid** [comment]
@alexlafroscia I added you on NPM as a maintainer. The command did not do what we want it to do since `adopted-ember-addons` is not a user. (According to the NPM CLI.)

**Comment by alexlafroscia** [comment]
Gotcha. I'll figure out how it works with organizations.

Thanks so much for your help here @stravid!

**Comment by scottkidder** [comment]
@alexlafroscia I'd like to be part of this repo, and maybe even `adopted-ember-addons` (I have a few other candidates I've been waiting on). Thanks to @stravid, @alexlafroscia and everyone else for improving the community!

**Comment by alexlafroscia** [comment]
@scottkidder excellent! I added you as a collaborator on the repo and will also give you the appropriate NPM privileges to publish releases
