### ISSUE TITLE
Calendar always opens in the current month when I am in some previous month

### ISSUE THREAD

**Issue by yagosenhorini** [adopted-ember-addons/ember-pikaday#203]
Hi there,
I have this problem:  My route always loads the current month normally, but when I select September month and update the page, the route will be September, but the calendar will open in October.
Is there a way to make the calendar opens in a month that I've selected before refreshing the page?

**Comment by alexlafroscia** [comment]
Could this be a timezone-related issue? For example, maybe one is using UTC and the other is not, and the time zones are far apart enough that one thinks it is September but the other thinks it is October?

I ask because today is the first day of October; have you seen this issue on other days?

**Comment by yagosenhorini** [comment]
I don't think so, because before this issue happened, the calendar always opened in the selected month, and yesterday was the first day that it happened.
I'll see if the problem is the UTC standard on the route and in the component. 
Thanks for this advice.
Is there a problem if I let this issue open?

**Comment by alexlafroscia** [comment]
Can you check today and see if the problem is still happening? 

I ran into off-by-one issues yesterday myself due to the UTC/non-UTC issue with dates.

**Comment by yagosenhorini** [comment]
Yes, I've checked this when I arrived at the work and the problem still happens.
I have no idea where the problem is in this case.

**Comment by alexlafroscia** [comment]
Can you create a reproduction using [Ember Twiddle](https://ember-twiddle.com/)? That would be really helpful in diagnosing the problem.

**Comment by yagosenhorini** [comment]
Hello Alex, how are you?
I've some problems with the Twiddle since yesterday.
I'm simulating only the calendar component, but the project is on infinity build and doesn't render the elements.
I'm trying to fix this now and I'll send to you after do this.
Sorry about that :(

**Comment by alexlafroscia** [comment]
I'm great, thanks for asking!

No problem about the Twiddle.

If it would be easier, do you want to send a full Ember application that shows the problem? That's honestly easier for me to debug anyway, and might be easier for you as well.

**Comment by yagosenhorini** [comment]
Hey Alex, I'm sending to you an URL to a dev Ember App, to test and debug as you wish :)

Link: https://dev-usage-dashboard.firebaseapp.com

There's an authentication at the first route.
The email is: calendartest@test.com and the password is: change1234

If you have any doubt about the template, just ask me.

Thanks for the help!

**Comment by yagosenhorini** [comment]
Hey man,
How are you doing?
Did you debug the project?
Is there anything that I could do to help you?

**Comment by alexlafroscia** [comment]
Sorry about the delay here! I'll try to check this out over the next day or two. It's still on my radar, don't worry!

**Comment by yagosenhorini** [comment]
Alright man.
If you need something, just ask me and I'll make the possible to help you!

**Comment by alexlafroscia** [comment]
Thanks for your patience here @yagosenhorini 

I checked out the site you gave me, that was _really_ helpful. I think I misunderstood your initial request request but totally "get it" now.

When you're using the Pikaday component, are you passing in a `value`? If you are, then the date month for that date should be visible right away, rather than showing the current month. Based on looking at the link you sent, it seems like maybe the `value` is missing.

**Comment by yagosenhorini** [comment]
Hey Alex, how are you?
Thanks for the answer.
I stopped to fix this, because I'm refactoring another project now, and this page that I've sent you will be included in this refactor.
But, I appreciate your help so much!
If it goes wrong, I'll report to you.

I'm closing this issue :)

**Comment by alexlafroscia** [comment]
Great! I'm happy to help in the future if there's still problems with the way the date picker works.
