### ISSUE TITLE
Month is undefined when using i18n

### ISSUE THREAD

**Issue by AleksandrBorovkov** [adopted-ember-addons/ember-pikaday#222]
I see months in initializer but in component it undefined.

![image](https://user-images.githubusercontent.com/22237897/57487995-8b6a6500-72ba-11e9-9e2a-918e0df8e5be.png)

![image](https://user-images.githubusercontent.com/22237897/57488167-fa47be00-72ba-11e9-8b3f-f15b13764736.png)

**Comment by AleksandrBorovkov** [comment]
I've fixed it with this
`months: moment.localeData()._months.standalone`

**Comment by drouhard** [comment]
For anyone finding this thread later, I found that the [above answer](https://github.com/adopted-ember-addons/ember-pikaday/issues/222#issuecomment-491089555) didn't work for all locales. I was able to solve the issue by using moment's standard `months()` function in the to get the appropriate values for each locale:
`months: moment.localeData().months()`
