### ISSUE TITLE
Close inputless by clicking anywhere on page

### ISSUE THREAD

**Issue by AleksandrBorovkov** [adopted-ember-addons/ember-pikaday#229]
Same as https://github.com/adopted-ember-addons/ember-pikaday/issues/130

Here is clean branch with reproduction.
https://github.com/AleksandrBorovkov/ember-test2

**Comment by alexlafroscia** [comment]
Just to makes sure that everyone on the original issue is kept up-to-date, I'm going to close this issue and re-open the original one!
