### ISSUE TITLE
Update ember-modifier to allow 4.x

### ISSUE THREAD

**Issue by cah-brian-gantzler** [adopted-ember-addons/ember-pikaday#550]
Please extend the range of ember modifier to use 3.x and 4.x

**Comment by tythewebguy** [comment]
I just wasted way too much time troubleshooting why `ember-pikaday` broke during my Ember 4 upgrade only to discover this fix has been committed to `master` but a new version has not been released. A version `4.0.1` would be really nice.

**Comment by cah-brian-gantzler** [comment]
:) Pretty sure I asked already a couple times to have a new release. You said ember 4, but think you mean ember-modifier 4 and yes, waiting on the same thing.

**Comment by tythewebguy** [comment]
I'm in the process of upgrading our project to Ember 4 and yes, `ember-pikaday` broke because of the `ember-modifier` version. Your post here helped me figure out the problem and get it fixed. You saved me a lot frustration—THANK YOU!

**Comment by cloutierlp** [comment]
It would be a real pleasure to see this problem resolved. Can we help in anyway?

**Comment by herzzanu** [comment]
Does the [latest release](https://github.com/adopted-ember-addons/ember-pikaday/releases/tag/v4.1.0-ember-pikaday) fix this?

**Comment by cah-brian-gantzler** [comment]
I believe it does.   


However now the `@ember/test-helpers' could use its range extended to include 3
